name: reinforcement_learning
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.21.0
  - pandas
  - pytorch
  - matplotlib
  - seaborn
  - pip
  - pip:
      - gym
