name: reinforcement_learning
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.1
  - pytorch
  - cudatoolkit=11.7
  - matplotlib
  - imageio
  - pip=21.0
  - pip:
      - gym==0.22.0
      - gym[atari,accept-rom-license]
      - opencv-python
